apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ambassador-backend
  name: ambassador-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ambassador-backend
  template:
    metadata:
      labels:
        io.kompose.service: ambassador-backend
    spec:
      containers:
        - args:
            - npm
            - run
            - start:dev
          env:
            - name: BOOTSTRAP_SERVERS
              value: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
            - name: DB_DATABASE
              value: ambassador
            - name: DB_HOST
              value: 34.93.151.246
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: ambassador_consumer
            - name: SASL_PASSWORD
              value: qT7k8wzjXZQY+X2B2Jfakb3b/VrGNfpugthG3JFZRRx4hLNuci79DSGV8kGM1Kix
            - name: SASL_USERNAME
              value: 442V3XBIVI6K43UW
            - name: USERS_MS
              value: http://users-backend:8001
          image: afsalkp/ambassador:0.0.1
          name: ambassador-backend
          ports:
            - containerPort: 3000
          
