version: '3'
services:
  ambassador_backend:
    build: .
    command: "npm run start:dev"
    image: afsalkp/ambassador:0.0.5
    ports:
      - 8003:3000
    environment:
      BOOTSTRAP_SERVERS: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
      SASL_USERNAME: 442V3XBIVI6K43UW
      SASL_PASSWORD: qT7k8wzjXZQY+X2B2Jfakb3b/VrGNfpugthG3JFZRRx4hLNuci79DSGV8kGM1Kix
      GROUP_ID:   ambassador_consumer
      DB_HOST: 34.93.151.246
      DB_PORT: 3306
      DB_DATABASE: ambassador
      DB_USERNAME: root
      DB_PASSWORD: root
      USERS_MS: http://users-backend:8001

  ambassador_consumer:
    build: .
    command: "npm run consume"
    image: afsalkp/ambassador:0.0.5
    environment:
      BOOTSTRAP_SERVERS: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
      SASL_USERNAME: 442V3XBIVI6K43UW
      SASL_PASSWORD: qT7k8wzjXZQY+X2B2Jfakb3b/VrGNfpugthG3JFZRRx4hLNuci79DSGV8kGM1Kix
      GROUP_ID:   ambassador_consumer
      DB_HOST: 34.93.151.246
      DB_PORT: 3306
      DB_DATABASE: ambassador
      DB_USERNAME: root
      DB_PASSWORD: root
      USERS_MS: http://users-backend:8001
    
  redis:
    image: redis
    ports:
      - 6379:6379

