apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: checkout-consumer
  name: checkout-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout-consumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: checkout-consumer
    spec:
      containers:
        - args:
            - npm
            - run
            - consume
          env:
            - name: BOOTSTRAP_SERVERS
              value: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
            - name: DB_DATABASE
              value: checkout
            - name: DB_HOST
              value: 35.200.235.207
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: checkout_consumer
            - name: SASL_PASSWORD
              value: qT7k8wzjXZQY+X2B2Jfakb3b/VrGNfpugthG3JFZRRx4hLNuci79DSGV8kGM1Kix
            - name: SASL_USERNAME
              value: 442V3XBIVI6K43UW
            - name: USERS_MS
              value: http://users-backend:8001
          image: afsalkp/checkout:0.0.1
          name: checkout-consumer
          resources: {}
      restartPolicy: Always
status: {}
